### ISSUE TITLE
Comment mentions converting InterVA input

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#10]
This mention of converting InterVA input is confusing. Should be fixed for better understanding and maintenance.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L296

**Comment by richardli** [comment]
c96b87a15acd850aa2e84659a0799e517544bd3f
