### ISSUE TITLE
Code could be condensed

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#11]
Could condense the following code to 
causes.train.out <- data.frame(ID = id.train, cause = causes.train, stringsAsFactors = F)

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L324-L325

**Comment by richardli** [comment]
fd540a8e6d256b9632fa89bb9e74f45eb27e8e25
