### ISSUE TITLE
Add more detail for use.rank in documentation

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#14]
It would be helpful for the user documentation to have more detailed information about what a 'TRUE' value means for use.rank in case they are not completely familiar with the algorithm.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L13

**Comment by richardli** [comment]
94c6f19dc742f3bffbcb4430a7a01448f63b975b
