### ISSUE TITLE
Code incorrectly sets top tariffs to zero

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#16]
The algorithm describes taking the top 40 Tariffs, but this code seems to be setting the top 40 Tariffs to zero thereby only looking at 41 to the end

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L235-L251

**Comment by richardli** [comment]
5ac9ff922e9c47f45c9a3fe47eb693edc78bb498

Bug fixed. Thank you. Silver lining is that use.top is default to FALSE.
