### ISSUE TITLE
Unnecessary assignment code can be removed

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#17]
Because of the join performed at line 318, it seems that line 321 is unnecessary. There should not be anything in CSMF that is not in causes.table2

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L317-L321

**Comment by richardli** [comment]
It is necessary. It reorders CSMF to user input.
