### ISSUE TITLE
if condition contains duplicated code

### ISSUE THREAD

**Issue by ghost** [verbal-autopsy-software/Tariff#3]
### if condition contains duplicated code
The code inside the `if` statement on line 323 is the same as what is outside at line 321 - is this intentional?

https://github.com/verbal-autopsy-software/Tariff/blob/5144ad844d7394ae6e72e87012929dc47d669b12/Tariff/R/Tariff.r#L321-L324

**Comment by richardli** [comment]
removed at 2324381cf330fc82f6022a950e7579fdee413271
