### ISSUE TITLE
Rename indices for readability

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#4]
The names colindex and colindex2 could be renamed to something having to do with train and test, respectively. This would improve readability and maintainability.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L54-L55

**Comment by richardli** [comment]
26158ce52dc68116bd3371c19b05e3e87789dd9f changed
