### ISSUE TITLE
Throw a warning if intersect removes some columns

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#7]
The code works and is harmless in intended case but it would be a good idea to alert the user.  If they inadvertently passed in the wrong dataset or something, a warning would catch it.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L78-L81

**Comment by richardli** [comment]
fcbf6073b65bd4880fe98c5353d879a785fbb2ee

**Comment by ghost** [comment]
These messages are very useful for the user, but I'm thinking that the if condition might need to be `if(length(joint) < length(colnames(symps.train)))` and `if(length(joint) < length(colnames(symps.test)))`, respectively?  As it stands, I think it's comparing a numeric integer to a vector.

**Comment by richardli** [comment]
22e2eed1447bf71969f41da2a12a8cf04f1d0ba6, thanks!
