### ISSUE TITLE
Check for upper and lower case

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#8]
Is it possible for y to be lower case here?  If so, recommendation to compare using 'toUpper()' just in case.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L118-L120

**Comment by richardli** [comment]
c96b87a15acd850aa2e84659a0799e517544bd3f
