### ISSUE TITLE
Rename causes.table2 to something more descriptive

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/Tariff#9]
The name causes.table2 does not help the reader/maintainer of the code to understand its meaning.  Suggestion is to rename to something more descriptive.

https://github.com/verbal-autopsy-software/Tariff/blob/2324381cf330fc82f6022a950e7579fdee413271/Tariff/R/Tariff.r#L193-L198

**Comment by richardli** [comment]
8a99bcb10320af09bae9d52e6bdea42d2ba0eade
